//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.09 at 10:10:23 AM CST 
//

package com.sinco.carnation.elong.model.elong;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;

import com.alibaba.fastjson.annotation.JSONField;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HotelGeo", propOrder = {"districts", "commericalLocations", "landmarkLocations"})
public class HotelGeoList {

	@JSONField(name = "Districts")
	@XmlElementWrapper(name = "Districts")
	@XmlElement(name = "LocationObj")
	private List<LocationObj> districts;
	@JSONField(name = "CommericalLocations")
	@XmlElementWrapper(name = "CommericalLocations")
	@XmlElement(name = "LocationObj")
	private List<LocationObj> commericalLocations;
	@JSONField(name = "LandmarkLocations")
	@XmlElementWrapper(name = "LandmarkLocations")
	@XmlElement(name = "LocationObj")
	private List<LocationObj> landmarkLocations;
	@XmlAttribute(name = "Country")
	private String country;
	@XmlAttribute(name = "ProvinceName")
	private String provinceName;
	@XmlAttribute(name = "ProvinceId")
	private String provinceId;
	@XmlAttribute(name = "CityName")
	private String cityName;
	@XmlAttribute(name = "CityCode")
	private String cityCode;

	public List<LocationObj> getDistricts() {
		return districts;
	}

	public void setDistricts(List<LocationObj> value) {
		this.districts = value;
	}

	public List<LocationObj> getCommericalLocations() {
		return commericalLocations;
	}

	public void setCommericalLocations(List<LocationObj> value) {
		this.commericalLocations = value;
	}

	public List<LocationObj> getLandmarkLocations() {
		return landmarkLocations;
	}

	public void setLandmarkLocations(List<LocationObj> value) {
		this.landmarkLocations = value;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String value) {
		this.country = value;
	}

	public String getProvinceName() {
		return provinceName;
	}

	public void setProvinceName(String value) {
		this.provinceName = value;
	}

	public String getProvinceId() {
		return provinceId;
	}

	public void setProvinceId(String value) {
		this.provinceId = value;
	}

	public String getCityName() {
		return cityName;
	}

	public void setCityName(String value) {
		this.cityName = value;
	}

	public String getCityCode() {
		return cityCode;
	}

	public void setCityCode(String value) {
		this.cityCode = value;
	}

}
