//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.09 at 10:10:23 AM CST 
//

package com.sinco.carnation.elong.model.elong;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.alibaba.fastjson.annotation.JSONField;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name ="HotelGeos")
@XmlType(name="hotelGeos",propOrder={"hotelGeoList"})
public class HotelGeos {

	@JSONField(name = "HotelGeoList")
	@XmlElementWrapper(name = "HotelGeoList")
	@XmlElement(name = "HotelGeo")
	private List<HotelGeoList> hotelGeoList;

	public List<HotelGeoList> getHotelGeoList() {
		return hotelGeoList;
	}

	public void setHotelGeoList(List<HotelGeoList> value) {
		this.hotelGeoList = value;
	}

}
